USE [master]
GO

/****** Object:  Database [SettleChat]    Script Date: 8/18/2020 6:21:32 PM ******/
CREATE DATABASE [SettleChat]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SettleChat', FILENAME = N'/var/opt/mssql/data/SettleChat.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SettleChat_log', FILENAME = N'/var/opt/mssql/data/SettleChat_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SettleChat].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SettleChat] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SettleChat] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SettleChat] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SettleChat] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SettleChat] SET ARITHABORT OFF 
GO

ALTER DATABASE [SettleChat] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SettleChat] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SettleChat] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SettleChat] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SettleChat] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SettleChat] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SettleChat] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SettleChat] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SettleChat] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SettleChat] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SettleChat] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SettleChat] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SettleChat] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SettleChat] SET ALLOW_SNAPSHOT_ISOLATION ON 
GO

ALTER DATABASE [SettleChat] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SettleChat] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [SettleChat] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SettleChat] SET RECOVERY FULL 
GO

ALTER DATABASE [SettleChat] SET  MULTI_USER 
GO

ALTER DATABASE [SettleChat] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SettleChat] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SettleChat] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SettleChat] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SettleChat] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SettleChat] SET QUERY_STORE = OFF
GO

ALTER DATABASE [SettleChat] SET  READ_WRITE 
GO


